@startuml
!include .\\b.puml
!include .\\Berthold.puml
!include .\\Equation.puml
!include .\\Program.puml
!include .\\Solve.puml
!include .\\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\obj\Debug\net6.0\Berthold1.AssemblyInfo.puml
!include .\\obj\Debug\net6.0\Berthold1.GlobalUsings.g.puml
@enduml
